apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: storage-bucket
spec:
  compositeTypeRef:
    apiVersion: custom-api.example.org/v1alpha1
    kind: storage
  resources:
    - name: s3Bucket
      base:
        apiVersion: s3.aws.upbound.io/v1beta1
        kind: Bucket
        metadata:
          name: crossplane-quickstart-s3bucket
        spec:
          forProvider:
            region: "ap-south-1"
          providerConfigRef:
            name: default